version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: blogger-mongo
    restart: always
    environment:
      MONGO_DB: ${DB_NAME}
      MONGO_USER: ${DB_USERNAME}
      MONGO_PASSWORD: ${DB_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
